### ISSUE TITLE
Locahost resolving

### ISSUE THREAD

**Issue by TwinUsers** [CustomIRCd/sIRCd#7]
I connected to a test server via 127.0.0.1 and with /etc/hosts having localhost domain setup it wouldn't resolve on the IRC. 

I've followed every guide, still don't work however it works fine using unrealircd. Is this something that could be fixed?

Thanks kindly

**Comment by CustomIRCd** [comment]
Hello,

Thanks for logging this, we will get the problem solved in the next release **1.0.7**

Regards
Ryan

**Comment by CustomIRCd** [comment]
@TwinUsers 

This is working just fine for me, feel free to Pop me a message on IRC and i'll happily help you get it working

Regards
Ryan
